# Generated by Django 5.2 on 2025-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('level', models.CharField(default='beginner', max_length=30)),
                ('enterprise', models.CharField(default='none', max_length=50)),
                ('software', models.CharField(default='default', max_length=50)),
                ('country', models.CharField(default='none', max_length=50)),
                ('address', models.CharField(default='none', max_length=255)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(default='none', max_length=40)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
